export const FETCH_MARKETS_START = 'FETCH_MARKETS_START';
export const FETCH_MARKETS_SUCCESS = 'FETCH_MARKETS_SUCCESS';
export const FETCH_MARKETS_FAILURE = 'FETCH_MARKETS_FAILURE';

export const FETCH_CHART_START = 'FETCH_CHART_START';
export const FETCH_CHART_SUCCESS = 'FETCH_CHART_SUCCESS';
export const FETCH_CHART_FAILURE = 'FETCH_CHART_FAILURE';

export const SET_BASE_CURRENCY = 'SET_BASE_CURRENCY';
export const TOGGLE_SELECTED_COIN = 'TOGGLE_SELECTED_COIN';
export const SET_SELECTED_COINS = 'SET_SELECTED_COINS';
export const SET_CHART_PERIOD = 'SET_CHART_PERIOD';
export const SET_CHART_TYPE = 'SET_CHART_TYPE';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';

export const SET_EXCHANGE_SELL_COIN = 'SET_EXCHANGE_SELL_COIN';
export const SET_EXCHANGE_BUY_COIN = 'SET_EXCHANGE_BUY_COIN';
export const SET_EXCHANGE_SELL_AMOUNT = 'SET_EXCHANGE_SELL_AMOUNT';
export const SET_EXCHANGE_VALIDATION_ERROR = 'SET_EXCHANGE_VALIDATION_ERROR';

export const FETCH_EXCHANGE_RATE_START = 'FETCH_EXCHANGE_RATE_START';
export const FETCH_EXCHANGE_RATE_SUCCESS = 'FETCH_EXCHANGE_RATE_SUCCESS';
export const FETCH_EXCHANGE_RATE_FAILURE = 'FETCH_EXCHANGE_RATE_FAILURE';
